import { useTranslation } from 'react-i18next';
import { Link } from 'react-router-dom';

const ListsPage = () => {
  const { t } = useTranslation();

  // Otomatik sistem listeleri
  const systemLists = [
    { id: 'watchlist', key: 'lists.system.watchlist', color: 'bg-blue-500/10 text-blue-400' },
    { id: 'watched', key: 'lists.system.watched', color: 'bg-brand-400/10 text-brand-400' }, // Senin yeşil tonun
    { id: 'favorites', key: 'lists.system.favorites', color: 'bg-red-500/10 text-red-400' },
  ];

  return (
    <div className="p-6 max-w-7xl mx-auto">
      {/* Header Bölümü */}
      <div className="flex items-center justify-between mb-10">
        <div>
          <h1 className="text-3xl font-display font-bold text-white">
            {t('lists.title', 'Listelerim')}
          </h1>
          <p className="text-slate-400 mt-1 text-sm">
            {t('lists.subtitle', 'Filmleri ve dizileri organize et.')}
          </p>
        </div>
        
        <button className="btn-primary flex items-center gap-2">
          <span>+</span> {t('lists.createNew', 'Yeni Liste')}
        </button>
      </div>

      {/* Sistem Listeleri Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-12">
        {systemLists.map((list) => (
          <Link
            key={list.id}
            to={`/lists/${list.id}`}
            className="group p-6 rounded-xl bg-slate-900/50 border border-slate-800 hover:border-brand-400/50 transition-all"
          >
            <div className={`w-10 h-10 rounded-lg ${list.color} flex items-center justify-center mb-4 font-bold`}>
              {/* İkon paketi yüklemediğimiz için ilk harfi ikon niyetine kullanıyoruz */}
              {t(list.key).charAt(0).toUpperCase()}
            </div>
            <h3 className="text-lg font-semibold text-white group-hover:text-brand-400 transition-colors">
              {t(list.key)}
            </h3>
            <p className="text-slate-500 text-sm mt-1">
              {t('lists.autoGenerated', 'Otomatik Oluşturuldu')}
            </p>
          </Link>
        ))}
      </div>

      {/* Özel Listeler Bölümü */}
      <div>
        <h2 className="text-xl font-display font-semibold text-white mb-6">
          {t('lists.customTitle')}
        </h2>
        
        {/* Boş Durum Tasarımı - Ana sayfadaki yapıya sadık */}
        <div className="flex flex-col items-center justify-center p-12 rounded-2xl border-2 border-dashed border-slate-800 text-center">
          <div className="text-slate-600 mb-4 text-4xl">📂</div>
          <p className="text-slate-400">
            {t('lists.noCustomLists')}
          </p>
          <button className="text-brand-400 hover:underline mt-2 text-sm font-medium">
            {t('lists.createFirst')}
          </button>
        </div>
      </div>
    </div>
  );
};

export default ListsPage;